FROM python:3.12-slim

WORKDIR /code

COPY pyproject.toml LICENSE README.md ./
COPY src/ src/
RUN pip install --no-cache-dir ".[api]"

COPY static/ static/
COPY fonts/ fonts/
COPY positron_style.json ./

EXPOSE 8000
CMD ["uvicorn", "hvv_map.api:app", "--host", "0.0.0.0", "--port", "8000"]
